package com.jssung.bookscannerreader
import android.content.Context
import org.json.*
import java.io.File
class LibraryStore(private val ctx:Context){
 private val file=File(ctx.filesDir,"library.json"); val books=mutableListOf<BookRecord>(); init{load()}
 fun addBook(b:BookRecord){books.add(b);save()}; fun deleteBook(b:BookRecord){books.removeAll{it.id==b.id};File(ctx.filesDir,"books/${b.id}").deleteRecursively();save()}
 fun save(){ val a=JSONArray(); books.forEach{b-> val o=JSONObject(); o.put("id",b.id);o.put("title",b.title);o.put("author",b.author);o.put("lastReadPage",b.lastReadPage);o.put("pdfPath",b.pdfPath);o.put("createdAt",b.createdAt); o.put("profile",JSONObject().apply{put("scanMode",b.profile.scanMode.name);put("targetWidth",b.profile.targetWidth);put("targetHeight",b.profile.targetHeight);put("splitRatio",b.profile.splitRatio.toDouble());put("readingDirection",b.profile.readingDirection.name);put("qualityThreshold",b.profile.qualityThreshold)}); val ps=JSONArray(); b.pages.forEach{p->ps.put(JSONObject().apply{put("id",p.id);put("index",p.index);put("imagePath",p.imagePath);put("ocrText",p.ocrText);put("qualityScore",p.qualityScore);put("note",p.note);put("bookmarked",p.bookmarked)})};o.put("pages",ps);a.put(o)}; file.writeText(a.toString()) }
 private fun load(){ if(!file.exists())return; runCatching{val a=JSONArray(file.readText());for(i in 0 until a.length()){val o=a.getJSONObject(i);val po=o.optJSONObject("profile");val b=BookRecord(id=o.getString("id"),title=o.getString("title"),author=o.optString("author"),profile=ScanProfile(scanMode=ScanMode.valueOf(po?.optString("scanMode","SPREAD")?:"SPREAD"),targetWidth=po?.optInt("targetWidth",1600)?:1600,targetHeight=po?.optInt("targetHeight",2400)?:2400,splitRatio=(po?.optDouble("splitRatio",.5)?:.5).toFloat(),readingDirection=ReadingDirection.valueOf(po?.optString("readingDirection","LEFT_TO_RIGHT")?:"LEFT_TO_RIGHT"),qualityThreshold=po?.optInt("qualityThreshold",65)?:65),lastReadPage=o.optInt("lastReadPage"),pdfPath=o.optString("pdfPath").takeIf{it.isNotBlank()&&it!="null"},createdAt=o.optLong("createdAt"));val ps=o.optJSONArray("pages")?:JSONArray();for(j in 0 until ps.length()){val p=ps.getJSONObject(j);b.pages.add(PageRecord(id=p.getString("id"),index=p.getInt("index"),imagePath=p.getString("imagePath"),ocrText=p.optString("ocrText"),qualityScore=p.optInt("qualityScore"),note=p.optString("note"),bookmarked=p.optBoolean("bookmarked")))};books.add(b)}} }
}
